# image will be published to ghcr.io/<user>/<name>
name: fexos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # OS-tree packages
  - from-file: custom/os-tree.yml
  # Flatpak packages
  - from-file: custom/flatpak.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

